import 'restaurant_model.dart';
import 'food_model.dart';

List<Food> sliderItems = [
  Food(
    imageUrl: 'assets/images/1.jpg',
    name: 'Burger',
    thumbsUp: 12,
    rating: 4,
    id: 'faksdfjald',
  ),
  Food(
    imageUrl: 'assets/images/2.jpeg',
    name: 'Pizza',
    thumbsUp: 8,
    rating: 3,
    id: 'faksdfjald23',
  ),
  Food(
    imageUrl: 'assets/images/3.jpg',
    name: 'Ugali',
    thumbsUp: 23,
    rating: 5,
    id: 'faksdfj234asdfald',
  ),
];

List<Food> foodSliderItems = [
  Food(
    imageUrl: 'assets/images/7.jpg',
    name: 'Burger',
    thumbsUp: 12,
    rating: 4,
    id: 'faksdfjald345lfa',
  ),
  Food(
    imageUrl: 'assets/images/5.jpg',
    name: 'Pizza',
    thumbsUp: 8,
    rating: 3,
    id: 'faksdfjfasdf89fald',
  ),
  Food(
    imageUrl: 'assets/images/4.png',
    name: 'Ugali',
    thumbsUp: 23,
    rating: 5,
    id: 'faksdf9f0sdfalfjald',
  ),
];

List<Restaurant> mostPopularRestaurants = [
  Restaurant(
    id: '12jfl',
    name: 'Java',
    imageUrl: 'assets/images/restaurant1.jpeg',
    address: '1047 Park Rd',
    location: 'Westlands',
    isRemoteImage: 0,
    description: 'Fried Chicken,American',
     rating: 1,
    menu: [
      Food(
        imageUrl: 'assets/images/1.jpg',
        name: 'Burger',
        thumbsUp: 12,
        rating: 4,
        id: 'faksdf32809fdsafjald',
      ),
      Food(
        imageUrl: 'assets/images/2.jpeg',
        name: 'Pizza',
        thumbsUp: 8,
        rating: 1,
        id: 'faksdf9fa239fjdfa-fjald',
      ),
      Food(
        imageUrl: 'assets/images/3.jpg',
        name: 'Ugali',
        thumbsUp: 23,
        rating: 5,
        id: '738rfsdlafads0123|',
      ),
    ],
  ),
  Restaurant(
    id: 'fkds0982',
    name: 'king Burger',
    imageUrl: 'https://clbrestaurants.com/portals/2/images/our-restaurants.jpg',
    address: 'Hse 112 Bay Area',
    location: 'California',
    isRemoteImage: 1,
    description: 'Brown Chapatis',
     rating: 4,
    menu: [
      Food(
        imageUrl: 'assets/images/4.png',
        name: 'Sushi',
        thumbsUp: 37,
        rating: 3,
        id: '83rfjlaZflka',
      ),
      Food(
        imageUrl: 'assets/images/5.jpg',
        name: 'KFC Chicken',
        thumbsUp: 18,
        rating: 5,
      ),
      Food(
        imageUrl:
            'https://www.prideinn.co.ke/assets/images/product/49/flavours-restaurants_flavours-restaurant.jpg',
        name: 'Fried Fish',
        thumbsUp: 90,
        imageIsRemote: 1,
        rating: 1,
        id: 'faksdf678fsfaaf}jald',
      ),
      Food(
        imageUrl: 'assets/images/7.jpg',
        name: 'Steamed Bananas',
        thumbsUp: 123,
        rating: 2,
        id: '1240980fajdfaf;faksdfjald',
      ),
      Food(
        imageUrl: 'assets/images/8.jpg',
        name: 'Onions Boiled',
        thumbsUp: 560,
        rating: 4,
        id: '8f789dafa23lfkaf]',
      ),
    ],
  ),
  Restaurant(
    id: 'fajlsd023e',
    name: 'Royal Porter',
    imageUrl: 'assets/images/restaurant2.jpg',
    address: '890 Kings Rd',
    location: 'Texas',
    isRemoteImage: 0,
    description: 'Grilled Chicken',
     rating: 2,
    menu: [
      Food(
        imageUrl: 'assets/images/7.jpg',
        name: 'Steamed Bananas',
        thumbsUp: 123,
        rating: 5,
        id: '12',
      ),
      Food(
        imageUrl: 'assets/images/2.jpeg',
        name: 'Pizza',
        thumbsUp: 8,
        rating: 3,
        id: '123',
      ),
      Food(
        imageUrl: 'assets/images/5.jpg',
        name: 'KFC Chicken',
        thumbsUp: 18,
        rating: 1,
        id: '657',
      ),
      Food(
        imageUrl:
            'https://www.prideinn.co.ke/assets/images/product/49/flavours-restaurants_flavours-restaurant.jpg',
        name: 'Fried Fish',
        thumbsUp: 90,
        imageIsRemote: 1,
        rating: 4,
        id: '430',
      ),
      Food(
        imageUrl: 'assets/images/4.png',
        name: 'Sushi',
        thumbsUp: 37,
        rating: 5,
        id: '50932',
      ),
      Food(
        imageUrl: 'assets/images/5.jpg',
        name: 'KFC Chicken',
        thumbsUp: 18,
        rating: 2,
        id: '23490fads',
      ),
      Food(
        imageUrl:
            'https://www.prideinn.co.ke/assets/images/product/49/flavours-restaurants_flavours-restaurant.jpg',
        name: 'Fried Fish',
        thumbsUp: 90,
        imageIsRemote: 1,
        rating: 4,
        id: '2343jfklajdlkJuLy',
      ),
      Food(
        imageUrl: 'assets/images/7.jpg',
        name: 'Steamed Bananas',
        thumbsUp: 123,
        rating: 5,
        id: 'June-sfsa+',
      ),
      Food(
        imageUrl: 'assets/images/8.jpg',
        name: 'Onions Boiled',
        thumbsUp: 560,
        rating: 2,
        id: '87fasdf&^',
      ),
    ],
  ),
  Restaurant(
    id: 'fasdfu98234p0',
    name: 'Mama Watoto',
    imageUrl: 'assets/images/restaurant3.jpg',
    address: '3-oswal hse',
    location: 'Munich',
    isRemoteImage: 0,
    description: 'Steamed Matoke',
     rating: 5,
    menu: [
      Food(
        imageUrl: 'assets/images/7.jpg',
        name: 'Steamed Bananas',
        thumbsUp: 123,
        rating: 1,
        id: '%jfklasdff09235',
      ),
      Food(
        imageUrl: 'assets/images/8.jpg',
        name: 'Onions Boiled',
        thumbsUp: 560,
        rating: 5,
        id: 'full-day',
      ),
      Food(
        imageUrl: 'assets/images/4.png',
        name: 'Sushi',
        thumbsUp: 37,
        rating: 3,
        id: 'passed-day-100',
      ),
      Food(
        imageUrl: 'assets/images/5.jpg',
        name: 'KFC Chicken',
        thumbsUp: 18,
        rating: 4,
        id: 'myday-in-3249832',
      ),
      Food(
        imageUrl:
            'https://www.prideinn.co.ke/assets/images/product/49/flavours-restaurants_flavours-restaurant.jpg',
        name: 'Fried Fish',
        thumbsUp: 90,
        imageIsRemote: 1,
        rating: 4,
        id: 'fjald8923)))',
      ),
    ],
  ),
  Restaurant(
    id: 'fas982734',
    name: 'Asian Restaurant',
    imageUrl: 'assets/images/restaurant4.jpg',
    address: 'Kenyatta avenue',
    location: 'Nairoib Cbd',
    isRemoteImage: 0,
    description: 'Pakistani Biriani',
    rating: 3,
    menu: [
      Food(
        imageUrl: 'assets/images/1.jpg',
        name: 'Burger',
        thumbsUp: 12,
        rating: 2,
        id: 'tuywe67:-',
      ),
      Food(
        imageUrl: 'assets/images/2.jpeg',
        name: 'Pizza',
        thumbsUp: 8,
        rating: 4,
        id: '{fjalkds7fasdf[]}',
      ),
      Food(
        imageUrl: 'assets/images/8.jpg',
        name: 'Onions Boiled',
        thumbsUp: 560,
        rating: 3,
        id: '9090-true',
      ),
      Food(
        imageUrl: 'assets/images/4.png',
        name: 'Sushi',
        thumbsUp: 37,
        rating: 5,
        id: 'better-for-100',
      ),
      Food(
        imageUrl: 'assets/images/5.jpg',
        name: 'KFC Chicken',
        thumbsUp: 18,
        rating: 5,
        id: 'wallah-here-109',
      ),
    ],
  ),
];

List<Food> mealDeals = [
  Food(
    imageUrl: 'assets/images/4.png',
    name: 'Sushi',
    thumbsUp: 37,
    rating: 4,
    id: 'sgsy7623',
  ),
  Food(
    imageUrl: 'assets/images/5.jpg',
    name: 'KFC Chicken',
    thumbsUp: 18,
    rating: 4,
    id: 'iosu7823shuys=',
  ),
  Food(
    imageUrl:
        'https://www.prideinn.co.ke/assets/images/product/49/flavours-restaurants_flavours-restaurant.jpg',
    name: 'Fried Fish',
    thumbsUp: 90,
    imageIsRemote: 1,
    rating: 3,
    id: 'asqwerty762',
  ),
  Food(
    imageUrl: 'assets/images/7.jpg',
    name: 'Steamed Bananas',
    thumbsUp: 123,
    rating: 3,
    id: 'meater-earter-001',
  ),
  Food(
    imageUrl: 'assets/images/8.jpg',
    name: 'Onions Boiled',
    thumbsUp: 560,
    rating: 5,
    id: 'politician-with-909',
  ),
];

List<Food> relatedFoods = [
  Food(
    imageUrl: 'assets/images/6.jpg',
    name: 'Osho',
    thumbsUp: 37,
    rating: 4,
    id: 'sgsy7623-fad',
  ),
  Food(
    imageUrl: 'assets/images/7.jpg',
    name: 'Dried Pig',
    thumbsUp: 18,
    rating: 4,
    id: 'iosu7823shuys=-fsdre',
  ),
  Food(
    imageUrl:
        'https://www.prideinn.co.ke/assets/images/product/49/flavours-restaurants_flavours-restaurant.jpg',
    name: 'Deep Fried Rat',
    thumbsUp: 90,
    imageIsRemote: 1,
    rating: 3,
    id: 'asqwerty762-rwer2',
  ),
  Food(
    imageUrl: 'assets/images/10.jpg',
    name: 'Sorough Banana',
    thumbsUp: 123,
    rating: 3,
    id: 'meater-earter-001-0fadsf342',
  ),
  Food(
    imageUrl: 'assets/images/1.jpg',
    name: 'Salad',
    thumbsUp: 560,
    rating: 5,
    id: 'politician-with-909-43fad9',
  ),
];
